language = "C"
header = "/* Test */"
include_version = true

# [parse]
# include = ["dome-key-map"]

[export]
include = ["KeyActionResult", "HeadphoneButton"]
# item_types = ["enums", "structs", "functions"]
item_types = ["constants", "globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]

[export.rename]
"run_key_action" = "hello_run"
