language = "C"
header = "/* Test */"
include_guard = "DOME_KEY_MAP_H"
include_version = true

# [parse]
# include = ["dome-key-map"]

[export]
include = ["HeadphoneButton", "MapKind"]
# item_types = ["enums", "structs", "functions"]
item_types = ["constants", "globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]

[export.rename]
"run_key_action" = "hello_run"

[enum]
prefix_with_name = true
